version: '3.3'
services:
  postgres:
    build:
      context: ./database
      dockerfile: postgres.dockerfile
    image: "postgres-demo"
    container_name: ${PG_CONTAINER_NAME}
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: ${PGDATA}
    volumes:
       - dbtuto:/data/postgres-tuto
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - sqlcoder_network

  ollama:
    image: "ollama/ollama"
    container_name: "ollama_container"
    depends_on:
      - postgres
    restart: unless-stopped
    ports:
      - "11434:11434"  # Port mapping for Ollama service
    networks:
      - sqlcoder_network
  
  python:
    build: ./python_files/

networks:
  sqlcoder_network:
    driver: bridge

volumes:
  dbtuto:
    external: true
